In [1]:
# written 2/9/22 by @ caramnix
# modified from Connectedness_Fowler2006.ipynb 
import os, json
import xmltodict
import numpy as np
import pandas as pd
import math

In [ ]:
#read in bill_dict

In [6]:
#now can read in easily! House 115 Data 
os.chdir("/Users/caranix/OneDrive - The Ohio State University/Social Influence/Data/Congress/115/House")
f = open('BILLSTATUS-115-hres-JSON.json')
Bill_Dict_H_115 = json.load(f)

In [ ]:
#added 3/30/22
Bill_Dict= Bill_Dict_H_115
#FOWLER VERSION OF COSPONSORSHIP 
#attach cosponsors to sponsors in directed fashion 
adjf_ = pd.DataFrame(index=u_id_nums, columns= u_id_nums)
adjf_ = adjf_.fillna(0)
for key in Bill_Dict: 
    sponser_id= Bill_Dict[str(key)]['sponser']['ID']
    num_cospo= len(Bill_Dict[str(key)]['cosponsers'])
    for i in range(0,num_cospo): 
        cospo_id= Bill_Dict[str(key)]['cosponsers'][i]["ID"]
        adjf_.loc[int(cospo_id)][int(sponser_id)] += 1

In [ ]:
#Bill_Dict_H_115.pop("765HRES") #error w/ this bill- cut.

In [7]:
#build w_ij, or the weighted quantity of cosponsored bills 
#id_nums is unique ID's of legislators 
#higher values --> more connected 
u_id_nums= pd.read_csv("leginfo_115H.csv")["ID"]
w_ij = pd.DataFrame(index=u_id_nums, columns= u_id_nums)
w_ij = w_ij.fillna(0)
for key in Bill_Dict_H_115: 
    #print(key)
    sponsor_id= int(Bill_Dict_H_115[key]['sponser']['ID'])
    n_cospos= len(Bill_Dict_H_115[key]['cosponsers'])
    if n_cospos == 0: 
        pass 
    else: 
        for i in range(0,n_cospos): 
            cospo_id= int(Bill_Dict_H_115[key]['cosponsers'][str(i)]["ID"])
            w_ij.loc[cospo_id,sponsor_id]= w_ij.loc[cospo_id,sponsor_id] + (1/n_cospos)

In [8]:
w_ij

ID,1997,1910,1593,2090,1751,1723,2319,2347,2222,1962,...,2248,711,977,2369,1560,2374,70,2375,2254,2372
ID,,,,,,,,,,,,,,,,,,,,,
1997,0.000000,1.590909,0.000000,0.027778,0.014085,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.035714,0.000,0,0.0,0,0,0.0,0,0
1910,1.919298,0.000000,0.046500,0.000000,0.000000,0.000000,0.5,0.017241,0.0,0.0,...,0.0,0.000000,0.025,0,0.0,0,0,0.0,0,0
1593,0.000000,0.034319,0.000000,0.000000,0.214286,0.035714,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
2090,0.158333,0.000000,1.123306,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
1751,0.000000,0.023810,0.020833,0.020408,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
70,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
2375,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
2254,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0
2372,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,...,0.0,0.000000,0.000,0,0.0,0,0,0.0,0,0

In [9]:
w_ij.to_csv("w_ij_cospo_house_115.csv")

In [26]:
#Bill_Dict_H_116['765HRES']

In [10]:
#now build d_ij- higher values --> less connected 
d_ij = 1/w_ij

In [11]:
d_ij

ID,1997,1910,1593,2090,1751,1723,2319,2347,2222,1962,...,2248,711,977,2369,1560,2374,70,2375,2254,2372
ID,,,,,,,,,,,,,,,,,,,,,
1997,inf,0.628571,inf,36.0,71.000000,inf,inf,inf,inf,inf,...,inf,28.0,inf,inf,inf,inf,inf,inf,inf,inf
1910,0.521024,inf,21.505244,inf,inf,inf,2.0,58.0,inf,inf,...,inf,inf,40.0,inf,inf,inf,inf,inf,inf,inf
1593,inf,29.138756,inf,inf,4.666667,28.0,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
2090,6.315789,inf,0.890229,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1751,inf,42.000000,48.000000,49.0,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
70,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
2375,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
2254,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
2372,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf

In [12]:
#https://www.algorithms-and-technologies.com/dijkstra/python
def dijkstra(graph, start):
    """
    Implementation of dijkstra using adjacency matrix.
    This returns an array containing the length of the shortest path from the start node to each other node.
    It is only guaranteed to return correct results if there are no negative edges in the graph. Positive cycles are fine.
    This has a runtime of O(|V|^2) (|V| = number of Nodes), for a faster implementation see @see ../fast/Dijkstra.java (using adjacency lists)

    :param graph: an adjacency-matrix-representation of the graph where (x,y) is the weight of the edge or 0 if there is no edge.
    :param start: the node to start from.
    :return: an array containing the shortest distances from the given start node to each other node
    """
    # This contains the distances from the start node to all other nodes
    distances = [float("inf") for _ in range(len(graph))]

    # This contains whether a node was already visited
    visited = [False for _ in range(len(graph))]

    # The distance from the start node to itself is of course 0
    distances[start] = 0

    # While there are nodes left to visit...
    while True:

        # ... find the node with the currently shortest distance from the start node...
        shortest_distance = float("inf")
        shortest_index = -1
        for i in range(len(graph)):
            # ... by going through all nodes that haven't been visited yet
            if distances[i] < shortest_distance and not visited[i]:
                shortest_distance = distances[i]
                shortest_index = i

        # print("Visiting node " + str(shortest_index) + " with current distance " + str(shortest_distance))

        if shortest_index == -1:
            # There was no node not yet visited --> We are done
            return distances

        # ...then, for all neighboring nodes that haven't been visited yet....
        for i in range(len(graph[shortest_index])):
            # ...if the path over this edge is shorter...
            if graph[shortest_index][i] != 0 and distances[i] > distances[shortest_index] + graph[shortest_index][i]:
                # ...Save this path as new shortest path.
                distances[i] = distances[shortest_index] + graph[shortest_index][i]
                # print("Updating distance of node " + str(i) + " to " + str(distances[i]))

        # Lastly, note that we are finished with this node.
        visited[shortest_index] = True
        # print("Visited nodes: " + str(visited))
        # print("Currently lowest distances: " + str(distances))

In [13]:
# dijkstras provides a matrix of shortest distances between each pair of legislators in the whole network 
dijkstra_mat = pd.DataFrame(index=u_id_nums, columns= u_id_nums)
dijkstra_mat = dijkstra_mat.fillna(0)

In [14]:
for i in range(0, len(u_id_nums)):     
    dijkstra_mat.iloc[i] = dijkstra(d_ij.to_numpy(),i)

In [15]:
dijkstra_mat

ID,1997,1910,1593,2090,1751,1723,2319,2347,2222,1962,...,2248,711,977,2369,1560,2374,70,2375,2254,2372
ID,,,,,,,,,,,,,,,,,,,,,
1997,0.000000,0.628571,3.400000,3.400000,3.518308,4.055331,2.628571,2.803226,4.003226,4.709877,...,4.582622,5.393202,2.945904,inf,6.504624,inf,inf,3.813953,inf,inf
1910,0.521024,0.000000,3.845065,3.456287,4.039332,4.032197,2.000000,2.174655,3.374655,4.686742,...,3.954050,5.213449,3.466928,inf,6.000000,inf,inf,4.151913,inf,inf
1593,3.336102,2.815078,0.000000,4.326715,3.075412,3.541319,4.160074,3.485206,3.822600,4.195865,...,3.427996,4.257695,3.859306,inf,5.369117,inf,inf,3.985798,inf,inf
2090,3.039142,3.667714,0.890229,0.000000,3.965642,4.431548,2.628352,2.803007,4.003007,5.086094,...,4.163387,5.147924,4.394759,inf,6.259347,inf,inf,4.550156,inf,inf
1751,3.159365,3.787937,4.585797,3.695568,0.000000,5.508899,4.614118,4.538394,5.692003,6.163445,...,5.054475,6.971754,4.645866,inf,7.534900,inf,inf,5.142456,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,2.839737,2.977143,4.266271,5.586694,3.243841,3.198339,4.977143,3.814262,4.123155,3.852885,...,4.002269,5.853205,5.335252,inf,5.964627,0.0,inf,2.956961,inf,inf
70,54.071542,53.550518,52.788145,55.719024,53.712670,53.667168,55.038717,54.283091,54.591983,54.321713,...,54.471097,55.650762,54.726088,inf,56.433456,inf,0.0,53.425789,inf,inf
2375,43.454992,43.592398,43.569028,45.238373,43.507257,43.762103,44.130284,42.742939,43.942939,44.416649,...,44.432591,45.628023,44.836452,inf,45.739446,inf,inf,0.000000,inf,inf
2254,5.603356,6.231928,5.681710,5.867029,4.000000,6.107417,5.242706,4.249875,5.449875,6.761963,...,3.922610,6.975886,6.149307,inf,8.212172,inf,inf,6.441340,0.0,inf
2372,56.719737,56.857143,60.119737,60.119737,59.270004,60.775068,58.857143,59.031798,60.231798,61.429614,...,60.811193,62.070592,59.665641,inf,62.857143,inf,inf,60.533690,inf,0.0

In [16]:
max(dijkstra_mat)

2375

In [17]:
dijkstra_mat= dijkstra_mat.replace([np.inf, -np.inf], np.nan)

In [18]:
maxElement1 = max(np.amax(dijkstra_mat, 1))
maxElement0 = max(np.amax(dijkstra_mat, 0))

In [19]:
maxElement1 = max(np.amax(dijkstra_mat, 1))
dijkstra_mat= dijkstra_mat.replace([np.nan], maxElement1 +1)

In [20]:
dijkstra_mat

ID,1997,1910,1593,2090,1751,1723,2319,2347,2222,1962,...,2248,711,977,2369,1560,2374,70,2375,2254,2372
ID,,,,,,,,,,,,,,,,,,,,,
1997,0.000000,0.628571,3.400000,3.400000,3.518308,4.055331,2.628571,2.803226,4.003226,4.709877,...,4.582622,5.393202,2.945904,94.0,6.504624,94.0,94.0,3.813953,94.0,94.0
1910,0.521024,0.000000,3.845065,3.456287,4.039332,4.032197,2.000000,2.174655,3.374655,4.686742,...,3.954050,5.213449,3.466928,94.0,6.000000,94.0,94.0,4.151913,94.0,94.0
1593,3.336102,2.815078,0.000000,4.326715,3.075412,3.541319,4.160074,3.485206,3.822600,4.195865,...,3.427996,4.257695,3.859306,94.0,5.369117,94.0,94.0,3.985798,94.0,94.0
2090,3.039142,3.667714,0.890229,0.000000,3.965642,4.431548,2.628352,2.803007,4.003007,5.086094,...,4.163387,5.147924,4.394759,94.0,6.259347,94.0,94.0,4.550156,94.0,94.0
1751,3.159365,3.787937,4.585797,3.695568,0.000000,5.508899,4.614118,4.538394,5.692003,6.163445,...,5.054475,6.971754,4.645866,94.0,7.534900,94.0,94.0,5.142456,94.0,94.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,2.839737,2.977143,4.266271,5.586694,3.243841,3.198339,4.977143,3.814262,4.123155,3.852885,...,4.002269,5.853205,5.335252,94.0,5.964627,0.0,94.0,2.956961,94.0,94.0
70,54.071542,53.550518,52.788145,55.719024,53.712670,53.667168,55.038717,54.283091,54.591983,54.321713,...,54.471097,55.650762,54.726088,94.0,56.433456,94.0,0.0,53.425789,94.0,94.0
2375,43.454992,43.592398,43.569028,45.238373,43.507257,43.762103,44.130284,42.742939,43.942939,44.416649,...,44.432591,45.628023,44.836452,94.0,45.739446,94.0,94.0,0.000000,94.0,94.0
2254,5.603356,6.231928,5.681710,5.867029,4.000000,6.107417,5.242706,4.249875,5.449875,6.761963,...,3.922610,6.975886,6.149307,94.0,8.212172,94.0,94.0,6.441340,0.0,94.0
2372,56.719737,56.857143,60.119737,60.119737,59.270004,60.775068,58.857143,59.031798,60.231798,61.429614,...,60.811193,62.070592,59.665641,94.0,62.857143,94.0,94.0,60.533690,94.0,0.0

In [24]:
dijkstra_mat.to_csv("d_ij_cospo_house_115.csv")

In [21]:
#this does what you want- sums rows (row sum is how connected legislator i is to everone else)
connectedness_score = pd.DataFrame(index=u_id_nums, columns= ["Connectedness"]) #select command + "" ==> quoting selection
num= len(u_id_nums)-1 
for i in range(0,len(dijkstra_mat)): 
    denom= sum(dijkstra_mat.iloc[i])
    connectedness_score.iloc[i]= num/denom

In [22]:
connectedness_score

     Connectedness
ID
1997      0.181959
1910      0.186174
1593      0.175515
2090      0.167891
1751      0.149338
...            ...
2374      0.166696
70        0.018091
2375      0.022122
2254       0.13548
2372      0.016465

[453 rows x 1 columns]

In [23]:
connectedness_score.to_csv("connectedness_house_115.csv")

In [31]:
#now can read in easily! House 116 Data 
os.chdir("/Users/caranix/OneDrive - The Ohio State University/Social Influence/Data/Congress/115/Senate")
f = open('BILLSTATUS-115-s-and-sres-JSON-dict.json')
Bill_Dict_S_115 = json.load(f)

In [35]:
#build w_ij, or the weighted quantity of cosponsored bills 
#id_nums is unique ID's of legislators 
#higher values --> more connected 
u_id_nums= pd.read_csv("leginfo_115S.csv")["ID"]
w_ij = pd.DataFrame(index=u_id_nums, columns= u_id_nums)
w_ij = w_ij.fillna(0)
for key in Bill_Dict_S_115: 
    #print(key)
    sponsor_id= int(Bill_Dict_S_115[key]['sponser']['ID'])
    n_cospos= len(Bill_Dict_S_115[key]['cosponsers'])
    if n_cospos == 0: 
        pass 
    else: 
        for i in range(0,n_cospos): 
            cospo_id= int(Bill_Dict_S_115[key]['cosponsers'][str(i)]["ID"])
            w_ij.loc[cospo_id,sponsor_id]= w_ij.loc[cospo_id,sponsor_id] + (1/n_cospos)

In [36]:
w_ij

ID,1010,1594,1464,1676,1692,2098,2175,2179,2079,2086,...,2366,1633,172,1695,1049,250,1825,1395,655,1548
ID,,,,,,,,,,,,,,,,,,,,,
1010,0.0,0.059618,0.000000,0.050000,0.114719,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.028723,0.175021,0.000000,0.0,0.022222,0.000000,0.054685,0.00,0
1594,0.0,0.000000,0.000000,0.000000,0.661226,0.540909,1.379727,0.000000,0.000000,0.055072,...,0.0,0.081633,0.000000,0.085145,0.0,0.022222,0.100852,0.020202,0.00,0
1464,0.0,0.694757,0.000000,0.071429,0.498564,0.526923,0.233894,0.692308,0.200000,0.471739,...,0.0,0.010204,0.015152,0.187500,0.0,0.151874,0.015625,0.042424,0.25,0
1676,0.0,0.194757,0.841116,0.000000,0.265670,0.052632,0.661275,0.500000,0.000000,0.632850,...,0.0,0.210204,0.037374,0.293478,0.0,0.000000,0.115379,1.020202,0.00,0
1692,0.0,0.505014,0.438302,0.142857,0.000000,0.469780,2.754565,0.282540,0.045455,0.515152,...,0.0,0.390760,0.666667,0.258756,0.0,0.055556,0.038352,0.042424,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,0.0,0.158249,0.105402,0.058824,0.312561,0.000000,0.171394,0.858974,0.090909,0.447930,...,0.0,0.717611,0.200000,0.000000,0.0,0.000000,0.015625,0.020202,0.00,0
1825,0.0,0.010101,0.000000,0.000000,0.575548,0.000000,0.000000,0.000000,0.000000,0.055072,...,0.0,0.010204,0.000000,4.772645,0.0,0.038462,0.000000,0.020202,0.00,0
1395,0.0,0.010101,0.000000,0.000000,0.043290,0.000000,0.041667,0.000000,0.000000,0.092446,...,0.0,0.010204,0.000000,0.243056,0.0,0.000000,0.000000,0.000000,0.00,0
655,0.0,0.010101,0.000000,0.000000,0.010101,0.000000,0.000000,0.000000,0.000000,0.018182,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0
1548,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.00,0

In [48]:
w_ij.to_csv("w_ij_cospo_senate_115.csv")

In [38]:
#now build d_ij- higher values --> less connected 
d_ij = 1/w_ij

In [39]:
d_ij

ID,1010,1594,1464,1676,1692,2098,2175,2179,2079,2086,...,2366,1633,172,1695,1049,250,1825,1395,655,1548
ID,,,,,,,,,,,,,,,,,,,,,
1010,inf,16.773481,inf,20.0,8.716981,inf,inf,inf,inf,inf,...,inf,34.815789,5.713607,inf,inf,45.000000,inf,18.286624,inf,inf
1594,inf,inf,inf,inf,1.512342,1.848739,0.724781,inf,inf,18.157895,...,inf,12.250000,inf,11.744681,inf,45.000000,9.915493,49.500000,inf,inf
1464,inf,1.439352,inf,14.0,2.005761,1.897810,4.275449,1.444444,5.0,2.119816,...,inf,98.000000,66.000000,5.333333,inf,6.584395,64.000000,23.571429,4.0,inf
1676,inf,5.134601,1.188896,inf,3.764063,19.000000,1.512231,2.000000,inf,1.580153,...,inf,4.757282,26.756757,3.407407,inf,inf,8.667066,0.980198,inf,inf
1692,inf,1.980145,2.281530,7.0,inf,2.128655,0.363034,3.539326,22.0,1.941176,...,inf,2.559118,1.500000,3.864644,inf,18.000000,26.074074,23.571429,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,inf,6.319149,9.487500,17.0,3.199375,inf,5.834525,1.164179,11.0,2.232494,...,inf,1.393512,5.000000,inf,inf,inf,64.000000,49.500000,inf,inf
1825,inf,99.000000,inf,inf,1.737474,inf,inf,inf,inf,18.157895,...,inf,98.000000,inf,0.209527,inf,26.000000,inf,49.500000,inf,inf
1395,inf,99.000000,inf,inf,23.100000,inf,24.000000,inf,inf,10.817102,...,inf,98.000000,inf,4.114286,inf,inf,inf,inf,inf,inf
655,inf,99.000000,inf,inf,99.000000,inf,inf,inf,inf,55.000000,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf
1548,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf,...,inf,inf,inf,inf,inf,inf,inf,inf,inf,inf

In [40]:
# dijkstras provides a matrix of shortest distances between each pair of legislators in the whole network 
dijkstra_mat = pd.DataFrame(index=u_id_nums, columns= u_id_nums)
dijkstra_mat = dijkstra_mat.fillna(0)

In [41]:
for i in range(0, len(u_id_nums)):     
    dijkstra_mat.iloc[i] = dijkstra(d_ij.to_numpy(),i)

In [42]:
dijkstra_mat

ID,1010,1594,1464,1676,1692,2098,2175,2179,2079,2086,...,2366,1633,172,1695,1049,250,1825,1395,655,1548
ID,,,,,,,,,,,,,,,,,,,,,
1010,0.000000,1.278741,1.164505,1.460362,0.892639,1.182660,0.823887,1.248577,1.313402,1.180041,...,1.570997,1.491085,1.070412,1.237252,1.328637,1.270966,1.343018,1.488113,5.164505,inf
1594,1.450259,0.000000,1.256584,1.452381,0.793533,1.306315,0.724781,1.241914,1.323051,1.564287,...,1.837242,0.809872,1.089487,1.464293,1.420716,1.292873,1.254766,1.291810,5.256584,inf
1464,1.459181,1.166589,0.000000,1.577887,0.730345,1.167063,1.000421,1.278548,0.960532,0.379884,...,1.440364,0.718700,1.247873,1.475889,0.725378,1.012262,1.266361,1.609648,4.000000,inf
1676,1.136824,1.269560,1.170990,0.000000,0.769854,1.267224,1.061648,0.841223,1.087947,1.305431,...,1.785440,0.758070,1.121447,1.342801,1.361201,0.889586,1.133274,0.980198,5.170990,inf
1692,1.096703,1.193592,0.637996,1.445726,0.000000,0.697807,0.363034,1.103787,1.151753,1.017880,...,1.517114,1.072459,1.324623,1.552639,0.802128,1.284668,1.343112,1.393576,4.637996,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,1.640370,1.732580,1.214678,1.829002,1.177044,1.274934,1.108292,1.164179,1.394503,1.383426,...,2.145745,1.219656,1.874633,1.969049,1.583117,0.000000,1.759522,1.937244,5.214678,inf
1825,2.242270,1.839184,2.180097,2.335580,1.737474,1.992890,1.976552,1.812223,2.291814,1.910295,...,2.475597,2.093851,2.005566,0.209527,2.344229,1.391671,0.000000,2.282242,5.992890,inf
1395,2.208722,2.485527,2.091187,2.477858,1.453191,2.123042,1.384439,2.167965,2.330898,2.471071,...,2.970305,2.428211,2.276117,2.521412,2.255319,2.676070,2.656026,0.000000,6.091187,inf
655,4.450742,4.358793,4.224264,3.485714,3.998970,4.262712,4.073512,4.020694,3.672552,4.393012,...,4.651049,4.004632,3.700619,4.590028,4.485190,4.375301,4.405177,4.465912,0.000000,inf
1548,28.009701,28.550735,27.996750,28.112451,27.764966,28.320014,28.128000,28.260816,27.968944,28.316956,...,28.239545,28.343911,27.549237,28.461861,28.160882,28.222624,28.533079,27.959302,31.996750,0.0

In [43]:
dijkstra_mat= dijkstra_mat.replace([np.inf, -np.inf], np.nan)

In [44]:
maxElement1 = max(np.amax(dijkstra_mat, 1))
dijkstra_mat= dijkstra_mat.replace([np.nan], maxElement1 +1)

In [45]:
#this does what you want- sums rows (row sum is how connected legislator i is to everone else)
connectedness_score = pd.DataFrame(index=u_id_nums, columns= ["Connectedness"]) #select command + "" ==> quoting selection
num= len(u_id_nums)-1 
for i in range(0,len(dijkstra_mat)): 
    denom= sum(dijkstra_mat.iloc[i])
    connectedness_score.iloc[i]= num/denom

In [46]:
connectedness_score

     Connectedness
ID
1010      0.654049
1594      0.637805
1464      0.706226
1676       0.74407
1692      0.711257
...            ...
250       0.563672
1825      0.434847
1395      0.387283
655       0.228569
1548      0.035482

[105 rows x 1 columns]

In [47]:
connectedness_score.to_csv("connectedness_senate_115.csv")